{
 "title": "WebLogic Server Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "domainName",
    "label": "Domain",
    "query": {
     "query": "label_values(weblogic_domainUID)"
    }
   },
   {
    "name": "clusterName",
    "label": "Cluster",
    "query": {
     "query": "label_values(weblogic_jvm_uptime{weblogic_domainUID=\"$domainName\"},weblogic_clusterName)"
    }
   },
   {
    "name": "serverName",
    "label": "Server",
    "query": {
     "query": "label_values(weblogic_jvm_uptime{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"},weblogic_serverName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Server Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "repeat": "serverName",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weblogic_server_activation_time{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\",weblogic_serverName=\"$serverName\"}"
    }
   ]
  },
  {
   "title": "Server Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 0 },
   "repeat": "serverName",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weblogic_server_stable_state{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}"
    }
   ]
  },
  {
   "title": "Running Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "repeat": "serverName",
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weblogic_jvm_uptime{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}"
    }
   ]
  },
  {
   "title": "Deployed Applications",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count(weblogic_application_active_version_state{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (name))"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - weblogic_jvm_heap_free_percent{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}"
    }
   ]
  },
  {
   "title": "JVM Current thread count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 3 },
   "repeat": "serverName",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_current{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}"
    }
   ]
  },
  {
   "title": "Open Sockets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 3 },
   "repeat": "serverName",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weblogic_server_open_sockets_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}"
    }
   ]
  },
  {
   "title": "DS Wait For Connection",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 3 },
   "repeat": "serverName",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (weblogic_serverName) (weblogic_jdbcdatasource_waiting_for_connection_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"})",
     "legendFormat": "{{weblogic_domainUID}}"
    }
   ]
  },
  {
   "title": "Stuck thread",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(weblogic_threadpool_stuck_thread_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (weblogic_threadpool_stuck_thread_count)"
    }
   ]
  },
  {
   "title": "Hogging thread",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(weblogic_threadpool_hogging_thread_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (weblogic_workmanager_hogging_thread_count)"
    }
   ]
  },
  {
   "title": "JVM CPU usage",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "weblogic_system_cpu_load{weblogic_domainUID=~\"$domainName\", weblogic_clusterName=~\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"} * 100"
    }
   ]
  },
  {
   "title": "Datasource Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "weblogic_jdbcdatasource_enabled{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"$serverName\"}"
    },
    {
     "expr": "weblogic_jdbcdatasource_waiting_for_connection_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"$serverName\"}"
    },
    {
     "expr": "irate(weblogic_jdbcdatasource_waiting_for_connection_failure_total{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}[1m])"
    },
    {
     "expr": "irate(weblogic_jdbcdatasource_waiting_for_connection_success_total{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}[1m])"
    },
    {
     "expr": "weblogic_jdbcdatasource_waiting_for_connection_failure_total{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}"
    }
   ]
  },
  {
   "title": "Applications Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "weblogic_application_webappcomponent_deployment_state{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"$serverName\"}"
    }
   ]
  },
  {
   "title": "Servers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM heap Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "JVM heap used ({{weblogic_serverName}})"
    },
    {
     "expr": "jvm_memory_bytes_max{area=\"heap\",weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "JVM heap max size ({{weblogic_serverName}})"
    }
   ]
  },
  {
   "title": "JVM Non heap Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\",weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "JVM non heap used ({{weblogic_serverName}})"
    },
    {
     "expr": "jvm_memory_bytes_max{area=\"nonheap\",weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "JVM non heap max ({{weblogic_serverName}})"
    }
   ]
  },
  {
   "title": "JVM heap Usage Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}/jvm_memory_bytes_max{area=\"heap\",weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}*100",
     "legendFormat": "JVM heap used ({{weblogic_serverName}})"
    }
   ]
  },
  {
   "title": "JVM Non heap Usage Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\",weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}/jvm_memory_bytes_max{area=\"nonheap\",weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}*100",
     "legendFormat": "JVM non heap used ({{weblogic_serverName}})"
    }
   ]
  },
  {
   "title": "Yuong Gen",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "G1 Eden Space Init Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_init{pool=\"G1 Eden Space\",weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "G1 Eden Space"
    }
   ]
  },
  {
   "title": "GC Time Young/per min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(jvm_gc_collection_seconds_sum{gc=\"G1 Young Generation\",weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}[1m])",
     "legendFormat": "{{gc}} ({{weblogic_serverName}})"
    }
   ]
  },
  {
   "title": "GC count Young/per min ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(jvm_gc_collection_seconds_count{gc=\"G1 Young Generation\",weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}[1m])",
     "legendFormat": "{{gc}} ({{weblogic_serverName}})"
    }
   ]
  },
  {
   "title": "Java Heap: Young",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"G1 Survivor Space\",weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "G1 Survivor Space ({{weblogic_serverName}})"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"G1 Eden Space\",weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "G1 Eden Space ({{weblogic_serverName}})"
    }
   ]
  },
  {
   "title": "Old Gen",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {}
   ]
  },
  {
   "title": "G1 Old Gen Init Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_init{pool=\"G1 Old Gen\",weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "G1 Old Gen"
    },
    {
     "expr": "jvm_memory_pool_bytes_commited{pool=\"G1 Old Gen\",weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}"
    }
   ]
  },
  {
   "title": "G1 Old Gen Max Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"G1 Old Gen\",weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}"
    }
   ]
  },
  {
   "title": "GC Time Old/per min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(jvm_gc_collection_seconds_sum{gc=\"G1 Old Generation\",weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}[1m])",
     "legendFormat": "{{gc}} ({{weblogic_serverName}})"
    }
   ]
  },
  {
   "title": "GC count Old/per min ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(jvm_gc_collection_seconds_count{gc=\"G1 Old Generation\",weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}[1m])",
     "legendFormat": "{{gc}} ({{weblogic_serverName}})"
    }
   ]
  },
  {
   "title": "Java Heap: Old",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"G1 Old Gen\",weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "G1 Old Gen ({{weblogic_serverName}})"
    }
   ]
  },
  {
   "title": "Metaspace",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Java Non Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Metaspace\",weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "Metaspace ({{weblogic_serverName}})"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Compressed Class Space\",weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "Compressed Class Space ({{weblogic_serverName}})"
    }
   ]
  },
  {
   "title": "Total Class loaded",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_classes_loaded_total{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "Total Class loaded"
    }
   ]
  },
  {
   "title": "Total Class Unloaded",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_classes_unloaded_total{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "Total Class Unloaded"
    }
   ]
  },
  {
   "title": "Current class loaded",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "Current Class loaded"
    }
   ]
  },
  {
   "title": "JVM Buffer Pool",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Buffer pool used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_pool_used_bytes{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "{{pool}} Buffer pool used  ({{weblogic_serverName}})"
    }
   ]
  },
  {
   "title": "JVM Buffer pool capacity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 63 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_pool_capacity_bytes{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "{{pool}} Buffer pool capacity  ({{weblogic_serverName}})"
    }
   ]
  },
  {
   "title": "JVM Buffer pool buffers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_pool_used_buffers{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "{{pool}} Buffer pool buffers  ({{weblogic_serverName}})"
    }
   ]
  },
  {
   "title": "JVM Thead Pool",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Thread Pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "threads_current ({{weblogic_serverName}})"
    },
    {
     "expr": "jvm_threads_daemon{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "threads_daemon ({{weblogic_serverName}})"
    },
    {
     "expr": "jvm_threads_peak{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "threads_peak ({{weblogic_serverName}})"
    },
    {
     "expr": "jvm_threads_deadlocked{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "threads_deadlock  ({{weblogic_serverName}})"
    }
   ]
  },
  {
   "title": "JVM Threads State",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state{state=\"BLOCKED\",weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "BLOCKED {{weblogic_serverName}}"
    },
    {
     "expr": "jvm_threads_state{state=\"TIMED_WAITING\",weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "TIMED_WAITING {{weblogic_serverName}}"
    },
    {
     "expr": "jvm_threads_state{state=\"NEW\",weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "NEW {{weblogic_serverName}}"
    },
    {
     "expr": "jvm_threads_state{state=\"WAITING\",weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "WAITING {{weblogic_serverName}}"
    },
    {
     "expr": "jvm_threads_state{state=\"TERMINATED\",weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "TERMINATED {{weblogic_serverName}}"
    },
    {
     "expr": "jvm_threads_state{state=\"RUNNABLE\",weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "RUNNABLE {{weblogic_serverName}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "weblogic_system_cpu_load{weblogic_domainUID=~\"$domainName\", weblogic_clusterName=~\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"} * 100",
     "legendFormat": " {{weblogic_serverName}}"
    }
   ]
  },
  {
   "title": "Thread Pool Total Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "weblogic_threadpool_execute_thread_total_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "Total Threads ({{weblogic_serverName}})"
    },
    {
     "expr": "weblogic_threadpool_stuck_thread_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "Stuck Threads ({{weblogic_serverName}})"
    }
   ]
  },
  {
   "title": "Web Applications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Sessions (top 10)",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "topk(30,sum(weblogic_application_webappcomponent_sessions_opened_total_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (application))"
    }
   ]
  },
  {
   "title": "Sessions Timeout (top 10)",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 84 },
   "targets": [
    {
     "expr": "topk(30,sum(weblogic_application_webappcomponent_session_timeout_secs{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (application))"
    }
   ]
  },
  {
   "title": "Total Sessions (top 10)",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 84 },
   "targets": [
    {
     "expr": "topk(30,sum(weblogic_application_webappcomponent_sessions_opened_total_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (application))"
    }
   ]
  },
  {
   "title": "Total Execution Time (top 10)",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 84 },
   "targets": [
    {
     "expr": "topk(10,sum(weblogic_application_execution_time_total{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (application))"
    }
   ]
  },
  {
   "title": "Current Sessions ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(weblogic_application_webappcomponent_open_sessions_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (application)) ",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Session Rate ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "short", "label": "per second" }
   ],
   "targets": [
    {
     "expr": "sum(irate(weblogic_application_webappcomponent_sessions_opened_total_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}[5m])) by (application)",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Execution Time per Request ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(sum(weblogic_application_execution_time_average{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (application)) / (count(weblogic_application_execution_time_average{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (application))",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Request Rate ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "short", "label": "per second" }
   ],
   "targets": [
    {
     "expr": "sum(irate(weblogic_application_invocation_total_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}[5m])) by (application)",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Weblogic Work Manager (WM)",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Stuck Thread Weblogic WM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "weblogic_application_workmanager_stuck_thread_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "{{application}} | WM: {{name}} ({{weblogic_serverName}})"
    }
   ]
  },
  {
   "title": "Hogging Thread Weblogic WM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 108 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "weblogic_threadpool_hogging_thread_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "WM: {{name}} ({{weblogic_serverName}})"
    }
   ]
  },
  {
   "title": "Completed requests Weblogic WM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(weblogic_application_workmanager_completed_requests{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}[1m])",
     "legendFormat": "{{application}} | WM: {{name}} ({{weblogic_serverName}})"
    }
   ]
  },
  {
   "title": "Pending requests Weblogic WM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "weblogic_application_workmanager_pending_requests{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "{{application}} | WM: {{name}} ({{weblogic_serverName}})"
    }
   ]
  },
  {
   "title": "ThreadPool queue length Weblogic WM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "weblogic_threadpool_queue_length{weblogic_domainUID=\"$domainName\",weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "{{application}} | WM: {{name}} ({{weblogic_serverName}})"
    }
   ]
  },
  {
   "title": "ThreadPool Overload Rejected Requests Weblogic WM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 130 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "weblogic_threadpool_overload_rejected_requests_count{weblogic_domainUID=\"$domainName\",weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "{{application}} | WM: {{name}} ({{weblogic_serverName}})"
    }
   ]
  },
  {
   "title": "ThreadPool throughput Weblogic WM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 138 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "weblogic_threadpool_throughput{weblogic_domainUID=\"$domainName\",weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "{{application}} | WM: {{name}} ({{weblogic_serverName}})"
    }
   ]
  },
  {
   "title": "Completed daemon requests Weblogic WM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 146 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "weblogic_application_workmanager_completed_daemon_requests{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "{{application}} | WM: {{name}} ({{weblogic_serverName}})"
    }
   ]
  },
  {
   "title": "Pending daemon requests Weblogic WM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 146 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "weblogic_application_workmanager_pending_daemon_requests{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "{{application}} | WM: {{name}} ({{weblogic_serverName}})"
    }
   ]
  },
  {
   "title": "Data Sources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 154 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Overview",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 155 },
   "targets": [
    {
     "expr": "sum(weblogic_jdbcdatasource_curr_capacity{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (weblogic_serverName,name)"
    },
    {
     "expr": "sum(weblogic_jdbcdatasource_active_connections_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (weblogic_serverName,name)"
    },
    {
     "expr": "sum(weblogic_jdbcdatasource_connections_total_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (weblogic_serverName,name)"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 161 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "weblogic_jdbcdatasource_active_connections_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": " {{name}} @ {{weblogic_serverName}}"
    }
   ]
  },
  {
   "title": "Connection Request Failures (per minute)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 161 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(weblogic_jdbcdatasource_failed_reserve_request_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}[1m])",
     "legendFormat": " {{name}} @ {{weblogic_serverName}}"
    }
   ]
  },
  {
   "title": "Datasource Wating Stats",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 167 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connection Requests that Waited (per minute)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 168 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(weblogic_jdbcdatasource_waiting_for_connection_total{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}[1m])",
     "legendFormat": "{{name}} @ {{weblogic_serverName}}"
    }
   ]
  },
  {
   "title": "Wait seconds high count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 168 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "weblogic_jdbcdatasource_wait_seconds_high_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}",
     "legendFormat": "{{name}} @ {{weblogic_serverName}}"
    }
   ]
  },
  {
   "title": "Connection Wait Successes (per minute)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 174 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(weblogic_jdbcdatasource_waiting_for_connection_success_total{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}[1m])",
     "legendFormat": "{{name}} @ {{weblogic_serverName}}"
    }
   ]
  },
  {
   "title": "Failed Waiting Connection Requests (per minute)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 174 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(weblogic_jdbcdatasource_waiting_for_connection_failure_total{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}[1m])",
     "legendFormat": "{{name}} @ {{weblogic_serverName}}"
    }
   ]
  },
  {
   "title": "Datasource Capacity",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 180 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Capacity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 181 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "weblogic_jdbcdatasource_curr_capacity{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}",
     "legendFormat": "{{name}} @ {{weblogic_serverName}}"
    }
   ]
  },
  {
   "title": "High num available",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 181 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "weblogic_jdbcdatasource_highest_num_available{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}",
     "legendFormat": "{{name}} @ {{weblogic_serverName}}"
    }
   ]
  },
  {
   "title": "Active connections high count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 187 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "weblogic_jdbcdatasource_active_connections_high_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}",
     "legendFormat": "{{name}} @ {{weblogic_serverName}}"
    }
   ]
  },
  {
   "title": "Connection Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 187 },
   "yaxes": [
    { "format": "short", "label": "per second" }
   ],
   "targets": [
    {
     "expr": "irate(weblogic_jdbcdatasource_connections_total_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}[1m])",
     "legendFormat": " {{name}} @ {{weblogic_serverName}}"
    }
   ]
  },
  {
   "title": "Datasource Prep Stmt Cache",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 193 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Hit count prep stmt cache",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 194 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(weblogic_jdbcdatasource_prep_stmt_cache_hit_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}[1m])",
     "legendFormat": "{{name}} @ {{weblogic_serverName}}"
    }
   ]
  },
  {
   "title": "Miss count prep stmt cache",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 194 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(weblogic_jdbcdatasource_prep_stmt_cache_miss_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}[1m])",
     "legendFormat": "{{name}} @ {{weblogic_serverName}}"
    }
   ]
  },
  {
   "title": "Current prep stmt cache size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 200 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "weblogic_jdbcdatasource_prep_stmt_cache_current_size{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}",
     "legendFormat": "{{name}} @ {{weblogic_serverName}}"
    }
   ]
  },
  {
   "title": "Access count prep stmt cache ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 200 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(weblogic_jdbcdatasource_prep_stmt_cache_access_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}[1m])",
     "legendFormat": "{{name}} @ {{weblogic_serverName}}"
    }
   ]
  },
  {
   "title": "Leaked connection count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 206 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "weblogic_jdbcdatasource_leaked_connection_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}",
     "legendFormat": "{{name}} @ {{weblogic_serverName}}"
    }
   ]
  },
  {
   "title": "Total connection count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 206 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "weblogic_jdbcdatasource_connections_total_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}",
     "legendFormat": "{{name}} @ {{weblogic_serverName}}"
    }
   ]
  },
  {
   "title": "Waiting for Connection High Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 212 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "weblogic_jdbcdatasource_waiting_for_connection_high_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}",
     "legendFormat": "{{name}} @ {{weblogic_serverName}}"
    }
   ]
  },
  {
   "title": "Waiting for Connection Current Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 212 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "weblogic_jdbcdatasource_waiting_for_connection_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}",
     "legendFormat": "{{name}} @ {{weblogic_serverName}}"
    }
   ]
  },
  {
   "title": "Connection delay time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 218 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "weblogic_jdbcdatasource_connection_delay_time{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": " {{name}} @ {{weblogic_serverName}}"
    }
   ]
  },
  {
   "title": "Average Connection Delay Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 218 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "weblogic_jdbcdatasource_connection_delay_time{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": " {{name}} @ {{weblogic_serverName}}"
    }
   ]
  },
  {
   "title": "JMS Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 224 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "JMS Connections",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(wls_jmsruntime_connections_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (weblogic_serverName)",
       "legendFormat": "{{weblogic_serverName}}"
      }
     ]
    },
    {
     "title": "JMS Connection Rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(wls_jmsruntime_connections_total_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}[5m])) by (weblogic_serverName)",
       "legendFormat": "{{weblogic_serverName}}"
      }
     ]
    },
    {
     "title": "JMSServer Overview",
     "type": "table-old",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 76 },
     "targets": [
      {
       "expr": "sum(wls_jms_destinations_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (jmsserver)"
      },
      {
       "expr": "sum(wls_jms_messages_received_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (jmsserver)"
      },
      {
       "expr": "sum(wls_jms_bytes_received_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (jmsserver)"
      },
      {
       "expr": "sum(wls_jms_destinations_total_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (jmsserver)"
      },
      {
       "expr": "sum(wls_jms_destinations_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (jmsserver)"
      }
     ]
    },
    {
     "title": "Messages",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(wls_jms_messages_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (jmsserver)",
       "legendFormat": "Current ({{jmsserver}})"
      },
      {
       "expr": "sum(wls_jms_messages_pending_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (jmsserver)",
       "legendFormat": "Pending ({{jmsserver}})"
      }
     ]
    },
    {
     "title": "Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(wls_jms_bytes_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (jmsserver)",
       "legendFormat": "Current ({{jmsserver}})"
      },
      {
       "expr": "sum(wls_jms_bytes_pending_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (jmsserver)",
       "legendFormat": "Pending ({{jmsserver}})"
      }
     ]
    },
    {
     "title": "Received Message Rate ",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 87 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(wls_jms_messages_received_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}[5m])) by (jmsserver)",
       "legendFormat": "{{jmsserver}}"
      }
     ]
    },
    {
     "title": "Received Byte Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 87 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(wls_jms_bytes_received_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}[5m])) by (jmsserver)",
       "legendFormat": "{{jmsserver}}"
      }
     ]
    },
    {
     "title": "Destinations Overview",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 94 },
     "targets": [
      {
       "expr": "sum(wls_jms_dest_consumers_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (destination)"
      },
      {
       "expr": "sum(wls_jms_dest_messages_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (destination)"
      },
      {
       "expr": "sum(wls_jms_dest_messages_pending_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (destination)"
      },
      {
       "expr": "sum(wls_jms_dest_bytes_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (destination)"
      },
      {
       "expr": "sum(wls_jms_dest_bytes_pending_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (destination)"
      },
      {
       "expr": "sum(wls_jms_dest_messages_received_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (destination)"
      },
      {
       "expr": "sum(wls_jms_dest_bytes_received_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (destination)"
      }
     ]
    }
   ]
  }
 ]
}